[project]
name = "exam-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "altair>=5.5.0",
    "image>=1.5.33",
    "pandas>=2.2.3",
    "polars>=1.17.1",
    "streamlit>=1.41.0",
]
